#spring:
#  mail:
#    host: smtp.qq.com
#    username: iphone5c@vip.qq.com
#    password: yydsnkxerlttbjja
#    port: 587
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls: true
#            enable: true
#            required: true
#    default-encoding: UTF-8


